// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenNoteAPI.Data;

#nullable disable

namespace OpenNoteAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220703221834_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OpenNoteAPI.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, incidunt?",
                            CreatedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4263),
                            ModifiedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4273),
                            Title = "Sample Note 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Odit iure quos quidem voluptate accusamus non officia maiores vero.",
                            CreatedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4276),
                            ModifiedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4277),
                            Title = "Sample Note 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Quos saepe tempora ipsam deserunt corrupti ipsum minima obcaecati minus.",
                            CreatedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4277),
                            ModifiedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4278),
                            Title = "Sample Note 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Possimus mollitia dolore placeat nisi nostrum cumque corrupti iste inventore!",
                            CreatedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4278),
                            ModifiedTime = new DateTime(2022, 7, 4, 1, 18, 34, 84, DateTimeKind.Local).AddTicks(4279),
                            Title = "Sample Note 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
